name: Quality
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Install Dependencies
        run: yarn install --prefer-offline --frozen-lockfile
      - name: Test
        run: make test

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Install Dependencies
        run: yarn install --prefer-offline --frozen-lockfile
      - name: Typecheck
        run: make typecheck
